# Generated by Django 4.2.2 on 2023-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='genre 1', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='artist 1', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
