# Generated by Django 4.2.2 on 2023-06-22 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0002_artist_name_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='songs_app.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='songs_app.genre'),
        ),
    ]
