# Generated by Django 4.2.2 on 2023-06-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0003_alter_song_artist_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
