# Generated by Django 4.2.2 on 2023-06-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0004_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=4),
        ),
    ]
